variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # The following wrappers essentially enter the respective
  # environment supporting these tools. This entails at least
  # source <path-to-installed-PetaLinux>/settings.sh (UG1144) or
  # source <Vitis Tool Installation Path>/settings64.sh (XD099)
  VIVADO_WRAPPER: "vitis-v2023.1.sh"
  PETALINUX_WRAPPER: "petalinux-v2023.1.sh"

stages:
  - vitis-project
  - psmake-build

.build_template:
  tags:
    - jammy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH =~ /^master/
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"

vitis_project_zcu102_xilinx: &vitis_project_zcu102_xilinx
  extends:
    - .build_template
  stage: vitis-project
  script:
    - mkdir -p vitis_project_zcu102_xilinx && cd vitis_project_zcu102_xilinx
    - cp -r ../examples/vitis/* .
    - rm default_7series.mk
    - ln -sf ../vitis.mk Makefile
  artifacts:
    paths:
      - vitis_project_zcu102_xilinx

vitis_project_zcu106_xilinx: &vitis_project_zcu106_xilinx
  extends:
    - .build_template
  stage: vitis-project
  script:
    - mkdir -p vitis_project_zcu106_xilinx && cd vitis_project_zcu106_xilinx
    - cp -r ../examples/vitis/* .
    - rm default_7series.mk
    - ln -sf ../vitis.mk Makefile
  artifacts:
    paths:
      - vitis_project_zcu106_xilinx

vitis_project_zc706_xilinx: &vitis_project_zc706_xilinx
  extends:
    - .build_template
  stage: vitis-project
  script:
    - mkdir -p vitis_project_zc706_xilinx && cd vitis_project_zc706_xilinx
    - cp -r ../examples/vitis/* .
    - mv default_7series.mk default.mk
    - ln -sf ../vitis.mk Makefile
  artifacts:
    paths:
      - vitis_project_zc706_xilinx

vitis_project_zc702_xilinx: &vitis_project_zc702_xilinx
  extends:
    - .build_template
  stage: vitis-project
  script:
    - mkdir -p vitis_project_zc702_xilinx && cd vitis_project_zc702_xilinx
    - cp -r ../examples/vitis/* .
    - mv default_7series.mk default.mk
    - ln -sf ../vitis.mk Makefile
  artifacts:
    paths:
      - vitis_project_zc702_xilinx

vitis_project_zed_xilinx: &vitis_project_zed_xilinx
  extends:
    - .build_template
  stage: vitis-project
  script:
    - mkdir -p vitis_project_zed_xilinx && cd vitis_project_zed_xilinx
    - cp -r ../examples/vitis/* .
    - mv default_7series.mk default.mk
    - ln -sf ../vitis.mk Makefile
  artifacts:
    paths:
      - vitis_project_zed_xilinx

vitis_project_zcu102-build:
  extends:
    - .build_template
  stage: psmake-build
  timeout: 1h
  script:
    - cd vitis_project_zcu102_xilinx
    - ${VIVADO_WRAPPER} make HW_PLAT=zcu102
  dependencies:
    - vitis_project_zcu102_xilinx

vitis_project_zcu106-build:
  extends:
    - .build_template
  stage: psmake-build
  timeout: 1h
  script:
    - cd vitis_project_zcu106_xilinx
    - ${VIVADO_WRAPPER} make HW_PLAT=zcu106
  dependencies:
    - vitis_project_zcu106_xilinx

vitis_project_zc706-build:
  extends:
    - .build_template
  stage: psmake-build
  timeout: 1h
  script:
    - cd vitis_project_zc706_xilinx
    - ${VIVADO_WRAPPER} make HW_PLAT=zc706
  dependencies:
    - vitis_project_zc706_xilinx

vitis_project_zc702-build:
  extends:
    - .build_template
  stage: psmake-build
  timeout: 1h
  script:
    - cd vitis_project_zc702_xilinx
    - ${VIVADO_WRAPPER} make HW_PLAT=zc702
  dependencies:
    - vitis_project_zc702_xilinx

vitis_project_zed-build:
  extends:
    - .build_template
  stage: psmake-build
  timeout: 1h
  script:
    - cd vitis_project_zed_xilinx
    - ${VIVADO_WRAPPER} make HW_PLAT=zed
  dependencies:
    - vitis_project_zed_xilinx
